GET http://localhost:3000/api/user/data

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InJvb3QiLCJlbWFpbCI6bnVsbCwiZGF0ZV9iaXJ0aCI6bnVsbCwibmFtZV91c2VyIjoicm9vdCIsImxhc3RfbmFtZSI6InJvb3QiLCJyb2xfaWQiOjEsImlhdCI6MTc1NjMyMjk4NiwiZXhwIjoxNzU2MzUxNzg2fQ.yg-W3e8RV_yqWuZn8dfpzVd7JAhU66Ao8QuFG_nxif4

###

GET  http://localhost:3000/api/user/data HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InJvb3QiLCJlbWFpbCI6bnVsbCwiZGF0ZV9iaXJ0aCI6bnVsbCwibmFtZV91c2VyIjoicm9vdCIsImxhc3RfbmFtZSI6InJvb3QiLCJyb2xfaWQiOjEsImlhdCI6MTc1NjMyMjk4NiwiZXhwIjoxNzU2MzUxNzg2fQ.yg-W3e8RV_yqWuZn8dfpzVd7JAhU66Ao8QuFG_nxif4